export const CREATE_LISTING_REQUEST = 'create_listing/CREATE_LISTING_REQUEST';
export const CREATE_LISTING_SUCCESS = 'create_listing/CREATE_LISTING_SUCCESS';
export const CREATE_LISTING_ERROR = 'create_listing/CREATE_LISTING_ERROR';

export const BOOTSTRAP_CREATE_LISTING = 'create_listing/BOOTSTRAP_CREATE_LISTING';
