# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  react-client:
    env_file: .env
    build:
      context: ./app
      dockerfile: Dockerfile.web
    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      S3_STATIC_BUCKET: ${S3_STATIC_BUCKET}
    ports:
      - "3000:3000"
    image:
      react-client  
  # Our Phoenix container
  phoenix:
    env_file: .env
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: .
    environment:
      # Variables to connect to our Postgres server
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_HOST: ${DB_HOST}
      GUARDIAN_SECRET_KEY: ${GUARDIAN_SECRET_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      S3_IMAGE_BUCKET_NAME: ${S3_IMAGE_BUCKET_NAME}
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
    image:
      offerdate:release
  db:
    # We use the predefined Postgres image
    image: postgres:10.3
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata: