# Version of docker-compose
version: '3.6'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix:
    env_file: .env
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: .
    environment:
      # Variables to connect to our Postgres server
      PG_USER: ${DB_USERNAME}
      PG_PASSWORD: ${DB_PASSWORD}
      PG_DATABASE: ${DB_NAME}
      PG_PORT: ${DB_PORT}
      # Hostname of our Postgres container
      PG_HOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
    image:
      offerdate:release
  db:
    # We use the predefined Postgres image
    image: postgres:10.3
    environment:
      # Set user/password for Postgres
      PG_USER: ${DB_USERNAME}
      PG_PASSWORD: ${DB_PASSWORD}
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata: