# Dockerfile
FROM node:9.6.1
ENV DEBIAN_FRONTEND=noninteractive
# The base node image sets a very verbose log level.
ENV NPM_CONFIG_LOGLEVEL warn
RUN mkdir /app
COPY . /app
ENV HOME=/app/ TERM=xterm
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
EXPOSE 3000
# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
# start app
RUN rimraf node_modules/.cache/babel-loader && next build
RUN NODE_ENV=production node index.js
