# Dockerfile
FROM node:9.6.1
ENV DEBIAN_FRONTEND=noninteractive
# The base node image sets a very verbose log level.
ENV NPM_CONFIG_LOGLEVEL warn
RUN mkdir /app
COPY . /app
ENV HOME=/app/ TERM=xterm
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
EXPOSE 3000
# install s3cmd to interact with amazon s3
RUN git clone https://github.com/s3tools/s3cmd.git /app/s3cmd
RUN ln -s /app/s3cmd/s3cmd /usr/bin/s3cmd
RUN apt-get -y update
#RUN apt-get install -y python-pip
RUN apt-get install python-dateutil
ENV S3_STATIC_BUCKET $S3_STATIC_BUCKET

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
# start app
RUN rimraf node_modules/.cache/babel-loader && next build
#RUN /app/configure_s3cmd.sh
#RUN s3cmd sync /app/build/* $S3_STATIC_BUCKET
CMD NODE_ENV=production node index.js
