use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :offerdate, Offerdate.Endpoint,
  load_from_system_env: true,
  http: [port: 4000],
  check_origin: false,
  url: [host: "${HOST}", port: 4000],
  secret_key_base: "${SECRET_KEY_BASE}",
  server: true

config :offerdate, Offerdate.Repo,
  adapter: Ecto.Adapters.Postgres,
  hostname: System.get_env("POSTRES_HOST"),
  username: System.get_env("POSTGRES_USER"),
  password: System.get_env("POSTGRES_PASSWORD"),
  database: System.get_env("POSTGRES_DATABASE"),
  pool_size: 20

# Do not print debug messages in production
config :logger, level: :info

# s3 config
config :s3,
  aws_access_key_id: System.get_env("AWS_ACCESS_KEY_ID"),
  aws_secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY"),
  image_bucket_name: System.get_env("S3_IMAGE_BUCKET_NAME")

# email (mailgun) 
config :offerdate, Offerdate.Mailer,
  adapter: Bamboo.MailgunAdapter,
  api_key: System.get_env("MAILGUN_KEY"),
  domain: System.get_env("MAILGUN_SANDBOX_DOMAIN"),
  from_email: "matt@offerdate.com",
  support_email: "matt@offerdate.com"

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :offerdate, Offerdate.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :offerdate, Offerdate.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :offerdate, Offerdate.Endpoint, server: true
#

# No longer using prod.secret.exs as we will be using environment vars instead
# Finally import the config/prod.secret.exs
# which should be versioned separately.
# import_config "prod.secret.exs"
