export const FETCH_SUGGESTIONS_REQUEST = 'offerDate/geocomplete/FETCH_SUGGESTIONS_REQUEST';
export const FETCH_SUGGESTIONS_SUCCESS = 'offerDate/geocomplete/FETCH_SUGGESTIONS_SUCCESS';
export const FETCH_SUGGESTIONS_ERROR = 'offerDate/geocomplete/FETCH_SUGGESTIONS_ERROR';
